"""users table

Revision ID: e2c5ff35a32e
Revises: 
Create Date: 2020-03-26 06:51:56.634170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2c5ff35a32e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authority', sa.String(length=140), nullable=True),
    sa.Column('brand', sa.String(length=140), nullable=True),
    sa.Column('size', sa.String(length=140), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('item_number', sa.String(length=140), nullable=True),
    sa.Column('daily_use', sa.Integer(), nullable=True),
    sa.Column('projected_daily_use', sa.Integer(), nullable=True),
    sa.Column('projected_run_out', sa.String(length=64), nullable=True),
    sa.Column('comments', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mask', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mask_timestamp'), ['timestamp'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('mask', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mask_timestamp'))

    op.drop_table('mask')
    # ### end Alembic commands ###
